### ISSUE TITLE
Getting errors installing 4.1.0.5498

### ISSUE THREAD

**Issue by ehmjaysee** [ABTSoftware/PodSpecs#1] opened 2020-10-01 02:20 UTC
I've been installing SciChart for a few years now without error, but this latest version is giving errors while running 'pod install' and I cannot compile my project. See console output below and Podfile below that.

mjc$ pod install
Analyzing dependencies
Downloading dependencies
Generating Pods project
Integrating client project
Pod installation complete! There are 21 dependencies from the Podfile and 36 total pods installed.

[!] Unable to read the license file `LICENSE.txt` for the spec `SciChart (4.1.0.5498)`

[!] Unable to read the license file `LICENSE.txt` for the spec `SciChart (4.1.0.5498)`

[!] Unable to read the license file `LICENSE.txt` for the spec `SciChart (4.1.0.5498)`

[!] Unable to read the license file `LICENSE.txt` for the spec `SciChart (4.1.0.5498)`

[!] Unable to read the license file `LICENSE.txt` for the spec `SciChart (4.1.0.5498)`

[!] Unable to read the license file `LICENSE.txt` for the spec `SciChart (4.1.0.5498)`

[!] Unable to read the license file `LICENSE.txt` for the spec `SciChart (4.1.0.5498)`

Relevant lines from Podfile:

```
source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/ABTSoftware/PodSpecs.git'
source 'https://github.com/ABTSoftware/PodSpecs-Nightly.git'

# Uncomment the next line to define a global platform for your project
platform :ios, '12.0'

inhibit_all_warnings!

target 'MotionIQ' do
  use_frameworks!
  pod 'Alamofire', '~> 4'
  pod 'SciChart',     '4.1.0.5498'  # 3.1.1.5312'
# pod 'SciChart',     '3.1.0-nightly.5301'
end
```

**Comment by ehmjaysee** [comment] 2020-10-01 16:19
Note: The same error happens if you create a new (empty) project and then add SciChart to the Podfile.

**Comment by nrudnyk** [comment] 2020-10-02 08:41
hello @ehmjaysee 
thanks for pointing the issue,  there were a wrong path to the LICENSE file in the podspec in latest version, which is now eliminated. 
Please try it out and let us know if the issue is gone.

**Comment by ehmjaysee** [comment] 2020-10-02 12:07
Progress. Now I can install the SciChart framework, and I can build my project for the simulator, however I get an error when building for any real iOS device:

`ld: building for iOS, but linking in dylib file (/Users/mjc/Library/Developer/Xcode/DerivedData/test2-ayogdvyjhuajllauzabcbybohkvo/Build/Products/Debug-iphoneos/SciChart.framework/SciChart) built for iOS Simulator, file '/Users/mjc/Library/Developer/Xcode/DerivedData/test2-ayogdvyjhuajllauzabcbybohkvo/Build/Products/Debug-iphoneos/SciChart.framework/SciChart' for architecture arm64
`

I created a new Xcode project and duped the problem.

**Comment by nrudnyk** [comment] 2020-10-02 13:22
What exact version of XCode and CocoaPods do you use? It seems that there is some issue with Xcode 12.0.1, which we are investigating...

In the meantime, you can install it manually by downloading a zip directly from the release assets and drag SciChart.xcframework to you project manually.

Another way is to use SPM (which has it's own issues and limitations):
https://www.scichart.com/documentation/ios/current/integrating-scichart-libraries.html#integrating-scichart-via-swift-package-manager

Let us know the details of your setup and if other methods work for you.

Thanks in advance

**Comment by ehmjaysee** [comment] 2020-10-02 13:46
Xcode Version 12.0.1 (12A7300)
pod version 1.9.3

Agree there is some speculation in the forums this problem may be affecting other pods as well.

**Comment by nrudnyk** [comment] 2020-10-02 14:02
ok, please try to update the CocoaPods to 1.10.0.rc.1, this should fix the problem.
https://github.com/CocoaPods/CocoaPods/releases/tag/1.10.0.rc.1

Please let us know if it works for you.

**Comment by andriypohorilko** [comment] 2020-10-02 14:13
Hi, there.
In order to install SciChart v.4 via CocoaPods you need to have CocoaPods version >= 1.10.0.rc.1.
You can install it using this command:
`sudo gem install cocoapods -v 1.10.0.rc.1`

To check your CocoaPods version use this command:
`pod --version`

Let us know if it helped.

**Comment by ehmjaysee** [comment] 2020-10-02 15:44
Confirmed. Pods 1.10.0.rc.1 fixed the problem.

**Comment by nrudnyk** [comment] 2020-10-02 15:51
great, closing then. Feel free to reopen if needed.
Best Regards

**Closed as completed by nrudnyk** 2020-10-02 15:51 UTC
